# Generated by Django 3.2.16 on 2023-02-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('customer', models.CharField(max_length=32, verbose_name='Customer')),
                ('product', models.CharField(max_length=64, verbose_name='Gem')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
