# Generated by Django 3.2.16 on 2023-02-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deals',
            options={'verbose_name': 'Deal', 'verbose_name_plural': 'Deals'},
        ),
        migrations.RenameField(
            model_name='deals',
            old_name='product',
            new_name='gems',
        ),
    ]
