# Generated by Django 3.2.16 on 2023-02-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_deals', '0002_auto_20230203_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deals',
            old_name='gems',
            new_name='gem',
        ),
    ]
